backend:
  name: github
  repo: guoyg578/arsovo
  branch: master
  base_url: https://arsovo.com
  auth_endpoint: api/auth

publish_mode: simple

media_folder: public/uploads
public_folder: /uploads

collections:
  - name: blog
    label: Blog Posts
    folder: src/content/blog
    create: true
    slug: "{{slug}}"
    extension: mdx
    format: frontmatter
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: text }
      - {
          label: Publish Date,
          name: pubDate,
          widget: datetime,
          format: YYYY-MM-DD,
          date_format: YYYY-MM-DD,
          time_format: false,
        }
      - { label: Tags, name: tags, widget: list, default: [] }
      - { label: Body, name: body, widget: markdown }
